"""`aspose-cells-mcp` — Cells' curated 8-tool MCP surface (Sprint 11, PRD Section 2.6/FR15b).

A genuinely separate, installable, versioned package (zero import dependency on the builder's own
`mcp_builder` — same Requirement 5.1 discipline `aspose-storage-core-mcp` established in Sprint 7,
extended here per Decision 4/Fork 1 Option A). No core/extra split (execution plan Fork 4) — it is
not a shared dependency of any other product, so every curated tool lives here.

Declares a real, ordinary versioned dependency on `aspose-storage-core-mcp` (`pyproject.toml`) for
the bundled core subset (`storage_upload_file`/`storage_download_file`/`storage_list_files`/
`storage_delete_file`, FR15b) — a user connected to only this server can still upload a file and get
its converted download, with no second server connection (this sprint's own exit criterion).
`generated/cells/server.py` is where that bundling actually happens; this package only owns Cells'
own tools.

**Real, live-verified finding (Sprint 11, this session): Cells' real API is `v3.0`, not `v4.0`.**
`v4.0` only provisions Cells' base download/convert route; every sub-resource operation
(documentproperties/worksheets/split/merge/replaceText/create) 404s/405s there with the identical
signature a nonexistent product namespace returns, but is fully live under `v3.0` — the same real
API-version gap Slides had (`codegen/spec.py`'s `_CELLS_OPERATION_SPECS` module comment has the full
account). This restores the original 8-operation curated set in full; the bundled Storage core-4
stays on `v4.0` for Cells specifically (that route genuinely works there, unlike Slides), with live-
confirmed cross-version storage interop.

Still deferred: `PutConvertWorkBook`'s real shape (the entire request body is the file, no named
parameter) and the three JSON-body operations (`SaveAs`/`Protect`/`Unprotect`) — not re-checked under
`v3.0` in this pass.

Regenerated by the builder's Codegen agent (`mcp_builder.codegen`) from the tracked, curated-subset
Cells IR — never hand-patched (rubric gate 8).
"""

from __future__ import annotations

from aspose_cells_mcp import tools
from aspose_cells_mcp.tools import (
    DeleteDocumentPropertiesResponse,
    GetDocumentPropertiesResponse,
    GetWorksheetsResponse,
    PostWorkbookSplitResponse,
    PostWorkbookTextReplaceResponse,
    PostWorkbooksMergeResponse,
    PutWorkbookCreateResponse,
    cells_create_workbook,
    cells_delete_workbook_properties,
    cells_download_workbook,
    cells_get_workbook_properties,
    cells_list_worksheets,
    cells_merge_workbooks,
    cells_replace_text,
    cells_split_workbook,
)

TOOL_ANNOTATIONS: dict[str, dict[str, object]] = {
    "cells_download_workbook": {
        "title": "Download an existing Cloud-stored Excel workbook in a given format",
        "read_only_hint": True,
        "destructive_hint": False,
        "idempotent_hint": True,
        "open_world_hint": True,
    },
    "cells_create_workbook": {
        "title": "Create a new Excel workbook in Aspose Cloud Storage",
        "read_only_hint": False,
        "destructive_hint": False,
        "idempotent_hint": False,
        "open_world_hint": True,
    },
    "cells_get_workbook_properties": {
        "title": "Get an Excel workbook's document properties",
        "read_only_hint": True,
        "destructive_hint": False,
        "idempotent_hint": True,
        "open_world_hint": True,
    },
    "cells_delete_workbook_properties": {
        "title": "Delete all of an Excel workbook's document properties",
        "read_only_hint": False,
        "destructive_hint": True,
        "idempotent_hint": True,
        "open_world_hint": True,
    },
    "cells_split_workbook": {
        "title": "Split an Excel workbook into separate worksheet files",
        "read_only_hint": False,
        "destructive_hint": False,
        "idempotent_hint": True,
        "open_world_hint": True,
    },
    "cells_merge_workbooks": {
        "title": "Merge another Excel workbook into an existing one",
        "read_only_hint": False,
        "destructive_hint": False,
        "idempotent_hint": False,
        "open_world_hint": True,
    },
    "cells_replace_text": {
        "title": "Replace text throughout an Excel workbook",
        "read_only_hint": False,
        "destructive_hint": False,
        "idempotent_hint": False,
        "open_world_hint": True,
    },
    "cells_list_worksheets": {
        "title": "List an Excel workbook's worksheets",
        "read_only_hint": True,
        "destructive_hint": False,
        "idempotent_hint": True,
        "open_world_hint": True,
    },
}

__all__ = [
    "tools",
    "cells_download_workbook",
    "cells_create_workbook",
    "cells_get_workbook_properties",
    "cells_delete_workbook_properties",
    "cells_split_workbook",
    "cells_merge_workbooks",
    "cells_replace_text",
    "cells_list_worksheets",
    "GetDocumentPropertiesResponse",
    "DeleteDocumentPropertiesResponse",
    "PutWorkbookCreateResponse",
    "PostWorkbooksMergeResponse",
    "PostWorkbookTextReplaceResponse",
    "PostWorkbookSplitResponse",
    "GetWorksheetsResponse",
    "TOOL_ANNOTATIONS",
]
