"""`aspose-cells-mcp`'s own standalone, runnable MCP server.

Auto-generated by Codegen's `generate_server_module_source` from the tracked IR — regenerate via
`run_lifecycle.py --product cells --action rebuild` instead of patching this file directly
(rubric gate 8: hand-patched generated output is a hard-gate failure, same discipline this
package's own `tools.py` header states).

This is the real runnable entry point the public `aspose-cells-mcp` package ships. Before
this file existed, the only actual MCP server for this product lived inside the private builder
repo's own staging area (its `generated/cells/server.py`), which imports the builder's own
internal auth client, tool-spec builder, IR document schema, lessons store, and semantic-db
modules directly, and loaded a live `ir/cells/*.json` snapshot at import time just to
recompute each tool's annotations and structured-output flag. None of that exists once this
package is the only thing actually published (Decision 6: every "published" release so far has
only ever been a GitLab tag of the *tools library*, `tools.py` — never a runnable server) — so
this file is a deliberate, self-contained rendering with **zero import dependency on the private
builder package**, mirroring every other file in this package's own zero-import-dependency-on-
the-builder discipline (see this package's own `_auth.py`/`_path_resolution.py` docstrings).
Every tool's annotations and
`structured_output` flag are baked into this file as literal values at the time it was
generated — never recomputed from a live IR file at server startup, since no IR file ships with
this package.

Bundles Storage's core-4 tools (FR15b) exactly like the existing staging-area servers do, so a
user connected to only this server can upload a file, operate on it, and download the result
with no second server connection.
"""

from __future__ import annotations

from typing import Any

from aspose_storage_core_mcp import (
    DeleteFileResponse,
    storage_delete_file,
    storage_download_file,
    storage_list_files,
    storage_upload_file,
)
from aspose_cells_mcp import (
    DeleteDocumentPropertiesResponse,
    GetDocumentPropertiesResponse,
    GetWorksheetsResponse,
    PostWorkbookSplitResponse,
    PostWorkbookTextReplaceResponse,
    PostWorkbooksMergeResponse,
    PutWorkbookCreateResponse,
    cells_create_workbook,
    cells_delete_workbook_properties,
    cells_download_workbook,
    cells_get_workbook_properties,
    cells_list_worksheets,
    cells_merge_workbooks,
    cells_replace_text,
    cells_split_workbook,
)
from aspose_cells_mcp._auth import AsposeAuthClient
from mcp.server.mcpserver import MCPServer
from mcp_types import ToolAnnotations


server = MCPServer(
    "aspose-cells",
    version="0.1.0",
    instructions="Real Codegen-generated MCP tools for Cells' curated operation set, plus Storage's bundled core subset (upload/download/list/delete).",
)


_auth: AsposeAuthClient | None = None


def _get_auth() -> AsposeAuthClient:
    global _auth
    if _auth is None:
        _auth = AsposeAuthClient()
    return _auth


# --- Bundled Storage core subset (FR15b) ----------------------------------------------------


def storage_upload_file_tool(filename: str, version_id: str | None = None, storage_name: str | None = None, content_base64: str | None = None, dry_run: bool = False) -> dict[str, Any]:
    # Sprint 11 real bug fix: `storage_upload_file`/`storage_delete_file` gained a `base_url`
    # parameter (Slides' v3.0 finding) inserted *before* `dry_run` in their real signatures -- a
    # positional call here would have silently passed `dry_run`'s value into `base_url` instead
    # (a real, confirmed bug, never actually exercised until now). Every storage-core call below is
    # keyword-only from this point on, immune to any future parameter reordering.
    return storage_upload_file(_get_auth(), "cells", filename, version_id=version_id, storage_name=storage_name, content_base64=content_base64, dry_run=dry_run)


def storage_download_file_tool(filename: str, version_id: str | None = None, storage_name: str | None = None, output_filename: str | None = None, return_base64: bool = False) -> dict[str, Any]:
    return storage_download_file(_get_auth(), "cells", filename, version_id=version_id, storage_name=storage_name, output_filename=output_filename, return_base64=return_base64)


def storage_list_files_tool(folder_name: str | None = None, storage_name: str | None = None) -> dict[str, Any]:
    return storage_list_files(_get_auth(), "cells", folder_name=folder_name, storage_name=storage_name)


def storage_delete_file_tool(filename: str, version_id: str | None = None, storage_name: str | None = None, dry_run: bool = False) -> DeleteFileResponse:
    return storage_delete_file(_get_auth(), "cells", filename, version_id=version_id, storage_name=storage_name, dry_run=dry_run)


_STORAGE_ANNOTATIONS = {
    "storage_upload_file": {"title": "Upload a file to Aspose Cloud Storage", "read_only_hint": False, "destructive_hint": False, "idempotent_hint": False},
    "storage_download_file": {"title": "Download a file from Aspose Cloud Storage", "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True},
    "storage_list_files": {"title": "List files in an Aspose Cloud Storage folder", "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True},
    "storage_delete_file": {"title": "Delete a file from Aspose Cloud Storage", "read_only_hint": False, "destructive_hint": True, "idempotent_hint": True},
}


_STORAGE_WRAPPERS = {
    "storage_upload_file": storage_upload_file_tool,
    "storage_download_file": storage_download_file_tool,
    "storage_list_files": storage_list_files_tool,
    "storage_delete_file": storage_delete_file_tool,
}

_STORAGE_REAL_FUNCS = {
    "storage_upload_file": storage_upload_file,
    "storage_download_file": storage_download_file,
    "storage_list_files": storage_list_files,
    "storage_delete_file": storage_delete_file,
}


# --- Cells' own curated tools ------------------------------------------------------------


def cells_download_workbook_tool(filename: str, target_format: str | None = None, auto_fit_rows: bool | None = None, only_save_table: bool | None = None, folder_name: str | None = None, output_path: str | None = None, storage_name: str | None = None, output_filename: str | None = None, return_base64: bool = False) -> dict[str, Any]:
    return cells_download_workbook(_get_auth(), filename=filename, target_format=target_format, auto_fit_rows=auto_fit_rows, only_save_table=only_save_table, folder_name=folder_name, output_path=output_path, storage_name=storage_name, output_filename=output_filename, return_base64=return_base64)


def cells_create_workbook_tool(filename: str, template_filename: str | None = None, data_filename: str | None = None, folder_name: str | None = None, storage_name: str | None = None, dry_run: bool = False) -> PutWorkbookCreateResponse:
    return cells_create_workbook(_get_auth(), filename=filename, template_filename=template_filename, data_filename=data_filename, folder_name=folder_name, storage_name=storage_name, dry_run=dry_run)


def cells_get_workbook_properties_tool(filename: str, folder_name: str | None = None, storage_name: str | None = None) -> GetDocumentPropertiesResponse:
    return cells_get_workbook_properties(_get_auth(), filename=filename, folder_name=folder_name, storage_name=storage_name)


def cells_delete_workbook_properties_tool(filename: str, folder_name: str | None = None, storage_name: str | None = None, dry_run: bool = False) -> DeleteDocumentPropertiesResponse:
    return cells_delete_workbook_properties(_get_auth(), filename=filename, folder_name=folder_name, storage_name=storage_name, dry_run=dry_run)


def cells_merge_workbooks_tool(filename: str, merge_with_filename: str, folder_name: str | None = None, storage_name: str | None = None, dry_run: bool = False) -> PostWorkbooksMergeResponse:
    return cells_merge_workbooks(_get_auth(), filename=filename, merge_with_filename=merge_with_filename, folder_name=folder_name, storage_name=storage_name, dry_run=dry_run)


def cells_replace_text_tool(filename: str, old_value: str, new_value: str, folder_name: str | None = None, storage_name: str | None = None, dry_run: bool = False) -> PostWorkbookTextReplaceResponse:
    return cells_replace_text(_get_auth(), filename=filename, old_value=old_value, new_value=new_value, folder_name=folder_name, storage_name=storage_name, dry_run=dry_run)


def cells_split_workbook_tool(filename: str, target_format: str | None = None, from_page: str | None = None, to_page: str | None = None, horizontal_resolution: str | None = None, vertical_resolution: str | None = None, folder_name: str | None = None, storage_name: str | None = None, dry_run: bool = False) -> PostWorkbookSplitResponse:
    return cells_split_workbook(_get_auth(), filename=filename, target_format=target_format, from_page=from_page, to_page=to_page, horizontal_resolution=horizontal_resolution, vertical_resolution=vertical_resolution, folder_name=folder_name, storage_name=storage_name, dry_run=dry_run)


def cells_list_worksheets_tool(filename: str, folder_name: str | None = None, storage_name: str | None = None) -> GetWorksheetsResponse:
    return cells_list_worksheets(_get_auth(), filename=filename, folder_name=folder_name, storage_name=storage_name)


_PRODUCT_ANNOTATIONS = {
    "cells_download_workbook": {"title": 'Download an existing Cloud-stored Excel workbook in a given format', "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True, "open_world_hint": True, "structured_output": False},
    "cells_create_workbook": {"title": 'Create a new Excel workbook in Aspose Cloud Storage', "read_only_hint": False, "destructive_hint": False, "idempotent_hint": False, "open_world_hint": True, "structured_output": True},
    "cells_get_workbook_properties": {"title": "Get an Excel workbook's document properties", "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
    "cells_delete_workbook_properties": {"title": "Delete all of an Excel workbook's document properties", "read_only_hint": False, "destructive_hint": True, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
    "cells_merge_workbooks": {"title": 'Merge another Excel workbook into an existing one', "read_only_hint": False, "destructive_hint": False, "idempotent_hint": False, "open_world_hint": True, "structured_output": True},
    "cells_replace_text": {"title": 'Replace text throughout an Excel workbook', "read_only_hint": False, "destructive_hint": False, "idempotent_hint": False, "open_world_hint": True, "structured_output": True},
    "cells_split_workbook": {"title": 'Split an Excel workbook into separate worksheet files', "read_only_hint": False, "destructive_hint": False, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
    "cells_list_worksheets": {"title": "List an Excel workbook's worksheets", "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
}


_PRODUCT_WRAPPERS = {
    "cells_download_workbook": cells_download_workbook_tool,
    "cells_create_workbook": cells_create_workbook_tool,
    "cells_get_workbook_properties": cells_get_workbook_properties_tool,
    "cells_delete_workbook_properties": cells_delete_workbook_properties_tool,
    "cells_merge_workbooks": cells_merge_workbooks_tool,
    "cells_replace_text": cells_replace_text_tool,
    "cells_split_workbook": cells_split_workbook_tool,
    "cells_list_worksheets": cells_list_worksheets_tool,
}


_PRODUCT_REAL_FUNCS = {
    "cells_download_workbook": cells_download_workbook,
    "cells_create_workbook": cells_create_workbook,
    "cells_get_workbook_properties": cells_get_workbook_properties,
    "cells_delete_workbook_properties": cells_delete_workbook_properties,
    "cells_merge_workbooks": cells_merge_workbooks,
    "cells_replace_text": cells_replace_text,
    "cells_split_workbook": cells_split_workbook,
    "cells_list_worksheets": cells_list_worksheets,
}


def _register_all_tools() -> None:
    # Storage core subset first (FR15b) — same 4 tools, same annotations, every rendered
    # server bundles.
    for name, wrapper in _STORAGE_WRAPPERS.items():
        annotations = _STORAGE_ANNOTATIONS[name]
        real_description = _STORAGE_REAL_FUNCS[name].__doc__
        server.add_tool(
            wrapper,
            name=name,
            title=annotations["title"],
            description=real_description or annotations["title"],
            annotations=ToolAnnotations(
                title=annotations["title"],
                read_only_hint=annotations["read_only_hint"],
                destructive_hint=annotations["destructive_hint"],
                idempotent_hint=annotations["idempotent_hint"],
                open_world_hint=True,
            ),
            structured_output=True,
        )

    # Cells' own curated tools.
    for name, wrapper in _PRODUCT_WRAPPERS.items():
        annotations = _PRODUCT_ANNOTATIONS[name]
        real_description = _PRODUCT_REAL_FUNCS[name].__doc__
        server.add_tool(
            wrapper,
            name=name,
            title=annotations["title"],
            description=real_description or annotations["title"],
            annotations=ToolAnnotations(
                title=annotations["title"],
                read_only_hint=annotations["read_only_hint"],
                destructive_hint=annotations["destructive_hint"],
                idempotent_hint=annotations["idempotent_hint"],
                open_world_hint=annotations["open_world_hint"],
            ),
            structured_output=annotations["structured_output"],
        )


_register_all_tools()


def main() -> None:
    server.run(transport="stdio")


if __name__ == "__main__":
    main()
